# -----------------------------------------------------------------------------
# ServiceMonitor for kube-state-metrics. Configures Prometheus to scrape metrics
# from the kube-state-metrics service for Kubernetes object state monitoring.
# -----------------------------------------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics-sm
    app.kubernetes.io/version: 2.17.0
  name: kube-state-metrics-sm
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      metricRelabelings:
        - action: drop
          regex: kube_(endpoint_(address_not_ready|address_available|ports))
          sourceLabels:
            - __name__
      port: metrics
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace_label_cluster]
          targetLabel: cluster
      scheme: http
      scrapeTimeout: 30s
    - interval: 30s
      port: metrics-self
      scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
