apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Shared resources and services used by multiple applications
  sourceRepos:
    - git@github.com:jackweinbender/infrastructure.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
