apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - configmap.yaml
  - secrets.yaml
  - deployment-server.yaml
  - deployment-ml.yaml
  - service-server.yaml
  - service-ml.yaml
  - httproute.yaml
  - monitor.yaml

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2

commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/part-of: immich
