# -----------------------------------------------------------------------------
# ServiceMonitor for node-exporter. Configures Prometheus to scrape metrics
# from the node-exporter DaemonSet for node-level monitoring.
# -----------------------------------------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-sm
    app.kubernetes.io/version: 1.9.1
    prometheus: system
  name: node-exporter-sm
spec:
  endpoints:
  - interval: 15s
    port: metrics
    relabelings:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    - action: replace
      sourceLabels: [__meta_kubernetes_namespace_label_cluster]
      targetLabel: cluster
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
