apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - monitor.yaml

configMapGenerator:
  - name: postgresql-conf
    files:
      - config/postgresql.conf

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: pgvector/pgvector
    newTag: pg17
