apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.6.2/install.yaml
  - gateway-class.yaml

patches:
  - path: patch-gateway-service.yaml
  - path: patch-envoygateway-configmap.yaml
    target:
      kind: ConfigMap
      name: envoy-gateway-config
      namespace: envoy-gateway-system
