apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homeassistant-endpointslice
  labels:
    kubernetes.io/service-name: homeassistant
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.1.194"
ports:
  - name: http
    port: 8123
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-ext
spec:
  hostnames:
    - homeassistant.ts.weinbender.io
  parentRefs:
    - name: tailnet-gateway
      namespace: tailscale
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - backendRefs:
        - kind: Service
          name: homeassistant
          namespace: external-services
          port: 8123
          group: ""
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
