apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: ExternalName
  externalName: homeassistant.weinbender.io
  ports:
    - name: http
      port: 8123
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-ext
spec:
  hostnames:
    - homeassistant.ts.weinbender.io
  parentRefs:
    - name: tailnet-gateway
      namespace: tailscale
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - backendRefs:
        - kind: Service
          name: homeassistant
          namespace: external-services
          port: 8123
          group: ""
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
