apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: homeassistant
  namespace: external-services
spec:
  endpoints:
    - fqdn:
        hostname: homeassistant.weinbender.io
        port: 8123
