apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  template:
    spec:
      volumes:
        - name: oauth
          secret: null
          projected:
            sources:
              - secret:
                  name: tailscale-client-id
                  items:
                    - key: token
                      path: client_id
              - secret:
                  name: tailscale-client-secret
                  items:
                    - key: token
                      path: client_secret
