apiVersion: v1
kind: Secret
metadata:
  name: tailscale-client-id
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/tailscale-oauth-k8s-operator/client-id"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-client-secret
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/tailscale-oauth-k8s-operator/client-secret"
type: Opaque
