apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vm-httproute
spec:
  hostnames:
    - victoriametrics.k8s.weinbender.io
  parentRefs:
    - name: cluster-gateway
      namespace: cluster-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - backendRefs:
        - kind: Service
          name: vmsingle-victoriametrics
          namespace: victoriametrics
          port: 8429
          group: ""
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
