apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoriametrics

resources:
  - https://github.com/VictoriaMetrics/operator/releases/download/v0.67.0/install-no-webhook.yaml
