apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: healthcheck
spec:
  hostnames:
    - healthcheck.k8s.weinbender.io
  parentRefs:
    - kind: Gateway
      name: cluster-gateway
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Service
          name: healthcheck
          port: 80
          group: ""
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: healthcheck-ts
spec:
  hostnames:
    - healthcheck.ts.weinbender.io
  parentRefs:
    - name: tailnet-gateway
      namespace: tailscale
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Service
          name: healthcheck
          port: 80
          group: ""
          weight: 1
