apiVersion: v1
kind: Secret
metadata:
  name: Infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "sshPrivateKey"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/argocd-microk8s-ssh-pk/privateKey"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:jackweinbender/infrastructure.git
  # sshPrivateKey: is the key that will be used to authenticate with the repository.
