apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      securityContext:
        # these settings ensure that homeassistant runs with the correct user and group IDs
        # which are necessary for file permissions on the host system
        runAsNonRoot: true
        runAsUser: 101000
        runAsGroup: 110000
        fsGroup: 110000
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: persistent-config
              mountPath: /config
            # Overlay static config files from ConfigMap using subPath
            - name: static-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              readOnly: true
            - name: static-config
              mountPath: /config/modules
              subPath: modules
              readOnly: true
      volumes:
        - name: persistent-config
          hostPath:
            path: /home/nas/shared/pvcs/homeassistant
            type: DirectoryOrCreate
        - name: static-config
          configMap:
            name: static-config
