apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

resources:
  - service.yaml
  - deployment.yaml
  - httproute.yaml

configMapGenerator:
  - name: config
    files:
      - config/configuration.yaml
      - config/modules/automations.yaml
      - config/modules/scripts.yaml
