apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

resources:
  - service.yaml
  - deployment.yaml
  - httproute.yaml
  - secrets.yaml

configMapGenerator:
  - name: static-config
    files:
      - config/configuration.yaml
