apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: immich
  namespace: immich
spec:
  hostnames:
    - immich.k8s.weinbender.io
  parentRefs:
    - kind: Gateway
      name: cluster-gateway
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Service
          name: immich-server
          namespace: immich
          port: 2283
          group: ""
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: immich-ts
  namespace: immich
spec:
  hostnames:
    - immich.ts.weinbender.io
  parentRefs:
    - name: tailnet-gateway
      namespace: tailscale
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Service
          name: immich-server
          namespace: immich
          port: 2283
          group: ""
          weight: 1
