apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: system
  source:
    path: kubernetes/manifests/system/envoy-gateway
    repoURL: git@github.com:jackweinbender/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
      - PruneLast=true
      # Use server-side apply for gateway resources
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
