apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoriametrics
    server: https://kubernetes.default.svc
  project: system
  source:
    path: kubernetes/manifests/system/victoriametrics-operator
    repoURL: git@github.com:jackweinbender/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
      - PruneLast=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
