apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-alloy

resources:
  - secrets.yaml

helmCharts:
  - name: alloy
    releaseName: alloy
    version: 1.6.0
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
