apiVersion: v1
kind: Secret
metadata:
  name: grafana-metrics-creds
  namespace: grafana-alloy
  annotations:
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana-tokens/metrics-token"
stringData:
  username: "933879"
  url: "https://prometheus-prod-13-prod-us-east-0.grafana.net./api/prom/push"
  # token will be synced by operator

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-logs-creds
  namespace: grafana-alloy
  annotations:
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana-tokens/logs-token"
stringData:
  username: "465908"
  url: "https://logs-prod-006.grafana.net./loki/api/v1/push"
  # token will be synced by operator

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-otlp-creds
  namespace: grafana-alloy
  annotations:
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana-tokens/otlp-token"
stringData:
  username: "616509"
  url: "https://otlp-gateway-prod-us-east-0.grafana.net./otlp"
  # token will be synced by operator

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-profiles-creds
  namespace: grafana-alloy
  annotations:
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana-tokens/profiles-token"
stringData:
  username: "616509"
  url: "https://profiles-prod-001.grafana.net.:443"
  # token will be synced by operator

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-fleet-mgmt-creds
  namespace: grafana-alloy
  annotations:
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana-tokens/fleet-mgt-token"
stringData:
  username: "616509"
  url: "https://fleet-management-prod-008.grafana.net"
  # token will be synced by operator
