apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.3/cert-manager.yaml
  - cloudflare-api-token.yaml
  - cluster-issuer-letsencrypt.yaml
  - cluster-wildcard-cert.yaml
