apiVersion: v1
kind: Secret
metadata:
  name: immich-database-password
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "secrets.yaml"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/homeassistant/admin-password"
type: Opaque
