# -----------------------------------------------------------------------------
# ServiceMonitor for the prometheus-operated Service, which manages the specific
# Prometheus instances that the Operator creates. This resource configures
# The Primary Prometheus instance to scrape all the Prometheus /metrics endpoints
# by default.
# -----------------------------------------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operated-sm
  labels:
    app.kubernetes.io/name: prometheus-operated-sm
    app.kubernetes.io/part-of: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      # Match all prometheus services created by the operator
      operated-prometheus: "true"
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
      scheme: http
      honorLabels: true
      honorTimestamps: true
---
# -----------------------------------------------------------------------------
# ServiceMonitor for the Prometheus Operator. This resource configures Prometheus
# to scrape metrics from the Prometheus Operator, which exposes information about
# the state of custom resources it manages (e.g., Prometheus, Alertmanager, ServiceMonitor).
# -----------------------------------------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-sm
  labels:
    app.kubernetes.io/name: prometheus-operator-sm
    app.kubernetes.io/part-of: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/component: controller
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: http
      honorLabels: true
      honorTimestamps: true
