apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana-credentials
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
    "k8s-secret-sync.weinbender.io/provider-name": "op"
    "k8s-secret-sync.weinbender.io/secret-key": "token"
    "k8s-secret-sync.weinbender.io/provider-ref": "op://microk8s/grafana/prometheus-token"
type: Opaque
stringData:
  token: <token>
  username: <user>
  uri: <uri>
