apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: kubernetes/manifests/apps/homeassistant
    repoURL: git@github.com:jackweinbender/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - Prune=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
