apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-wildcard-tls
spec:
  secretName: cluster-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.ts.weinbender.io"
  dnsNames:
    - "*.ts.weinbender.io"
    - "ts.weinbender.io"
  usages:
    - digital signature
    - key encipherment
    - server auth
