apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/tags/v1.92.4/cmd/k8s-operator/deploy/manifests/operator.yaml
  - secrets.yaml
  - envoy-gateway-class.yaml
  - envoy-gateway.yaml
  - envoy-httproute-default.yaml
  - envoy-proxy.yaml
  - cluster-wildcard-cert.yaml

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: operator
  - path: patch-secrets.yaml
    # Patch to replace the operator-oauth secret
    # used by the operator deployment, We don't want it.
    target:
      kind: Secret
      name: operator-oauth
